### PR TITLE
Issue #435

### PR DESCRIPTION
**Pull request by Bdish22**

### CODE REVIEW

**Comment by jhs507** [comment]
Thank you for this fix Brenden. 

@loganxingfang I have assigned you to review this fix. 

If you think it solves the issue I will merge it.

**Comment by loganxingfang** [comment]
> Thank you for this fix Brenden.
> 
> @loganxingfang I have assigned you to review this fix.
> 
> If you think it solves the issue I will merge it.

@jhs507 I reviewed this code change. It is good. As this is also a bug in Borland CRHM ClassSoilX, I will put this fix in later. The only thing I might do differently is to use 0.0 when comparing to floating value of Zd_front_array[0][hh]

if (NO_Freeze[hh] || Zd_front_array[0][hh] == 0.0)

**Comment by jhs507** [comment]
That is a good catch. I think we should add the 0.0 in now. Instead of reverting the commit I will just make a new one with the edit.

**Comment by jhs507** [comment]
Actually, since No_Freeze is a long and Zd_front_array is a double I altered it to test the long against 0 and the double against 0.0

103e6ca04a145c6b95c5c9f5a633a71390b19589 here is the commit.

**Pull request merged**
